project_id = "zyhmwcsfifdepqnnrguo"

[functions.register-push-subscription]
verify_jwt = true

[functions.hotmart-webhook]
verify_jwt = false

[functions.validate-token]
verify_jwt = false

[functions.activate-subscription]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-status-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = true

[functions.whatsapp-process-text]
verify_jwt = true

[functions.whatsapp-process-image]
verify_jwt = true

[functions.whatsapp-scheduled-reminders]
verify_jwt = true

[functions.revenuecat-webhook]
verify_jwt = false

[functions.whatsapp-send-reminders]
verify_jwt = false

[functions.whatsapp-weekly-objectives]
verify_jwt = false

[functions.ai-goals-calculator]
verify_jwt = false

[functions.identify-dish]
verify_jwt = false

[functions.generate-home-recipe]
verify_jwt = false

[functions.suggest-baby-names]
verify_jwt = true

[functions.generate-baby]
verify_jwt = true

[functions.generate-social-caption]
verify_jwt = true

[functions.generate-social-image]
verify_jwt = true

[functions.generate-weekly-ideas]
verify_jwt = true

[functions.generate-post-recipe]
verify_jwt = true

[functions.venue-mystery-hint]
verify_jwt = false
