project_id = "zyhmwcsfifdepqnnrguo"

[functions.register-push-subscription]
verify_jwt = true

[functions.hotmart-webhook]
verify_jwt = false

[functions.validate-token]
verify_jwt = false

[functions.activate-subscription]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-status-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = true

[functions.whatsapp-process-text]
verify_jwt = true

[functions.whatsapp-process-image]
verify_jwt = true

[functions.whatsapp-scheduled-reminders]
verify_jwt = true

[functions.revenuecat-webhook]
verify_jwt = false

[functions.whatsapp-send-reminders]
verify_jwt = false

[functions.whatsapp-weekly-objectives]
verify_jwt = false
