-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQga0FeRu/htDWJGNxj
juFKeNF+jctjl0ULD5C1jQTclWOgCgYIKoZIzj0DAQehRANCAARAu12eQc/WSzKu
WnePJVBFC1qDhuqD+xwDOwJCDrePlz+KX6TP7+Vq+o30aWSCVkOalIHumZq9+N0X
CM2QipAl
-----END PRIVATE KEY-----