export type CategoryCopy = { title: string; subtitle: string };

export const CATEGORY_COPY: Record<string, CategoryCopy> = {
  mercearia: { title: "O básico que não pode faltar", subtitle: "Arroz, feijão, óleo e mais perto de você." },
  bebidas: { title: "Pra matar a sede", subtitle: "Refrigerantes, sucos e muito mais." },
  "bebidas-geladas": { title: "Geladinha do jeito que você gosta", subtitle: "Tudo direto da geladeira pra sua casa." },
  hortifruti: { title: "Fresquinho todo dia", subtitle: "Frutas, verduras e legumes selecionados." },
  "frutas-e-verduras": { title: "Direto da feira", subtitle: "Frutas e verduras fresquinhas pra sua mesa." },
  frutas: { title: "Doçura da natureza", subtitle: "As frutas mais frescas, na sua porta." },
  verduras: { title: "Verde que faz bem", subtitle: "Folhas frescas, colhidas com cuidado." },
  legumes: { title: "Sabor da terra", subtitle: "Legumes selecionados pra suas receitas." },
  padaria: { title: "Quentinho saindo do forno", subtitle: "Pães, bolos e delícias artesanais." },
  paes: { title: "Crocante por fora, macio por dentro", subtitle: "Pães fresquinhos todos os dias." },
  limpeza: { title: "Casa brilhando", subtitle: "Tudo para deixar seu lar impecável." },
  higiene: { title: "Cuidado que faz diferença", subtitle: "Produtos essenciais pra rotina." },
  "higiene-pessoal": { title: "Bem-estar pra você", subtitle: "Higiene e cuidado pessoal." },
  pet: { title: "Amor de quatro patas", subtitle: "Tudo pro melhor amigo." },
  bebes: { title: "Cuidado especial pros pequenos", subtitle: "Tudo pra fase mais doce." },
  cafes: { title: "Aquele cheirinho de café", subtitle: "Pra começar bem o seu dia." },
  laticinios: { title: "Frescor todo dia", subtitle: "Leite, queijos e iogurtes selecionados." },
  "laticinios-ovos": { title: "Da fazenda pra sua mesa", subtitle: "Laticínios e ovos fresquinhos." },
  "carnes-e-aves": { title: "Sabor da boa carne", subtitle: "Cortes selecionados, prontos pra sua receita." },
  "carnes-aves": { title: "Sabor da boa carne", subtitle: "Cortes selecionados, prontos pra sua receita." },
  "carnes-bovinas": { title: "O melhor da picanha à alcatra", subtitle: "Cortes nobres pro seu churrasco." },
  "carnes-suinas": { title: "Sabor que conquista", subtitle: "Cortes suínos selecionados." },
  aves: { title: "Leve e saboroso", subtitle: "Frango fresquinho pra suas receitas." },
  peixes: { title: "Direto do mar", subtitle: "Peixes frescos selecionados." },
  "frutos-do-mar": { title: "Sabor do oceano", subtitle: "Frutos do mar pra ocasiões especiais." },
  frios: { title: "Pra montar a tábua perfeita", subtitle: "Frios selecionados e cheios de sabor." },
  congelados: { title: "Praticidade no freezer", subtitle: "Sempre prontos quando a fome bater." },
  doces: { title: "Pra adoçar o dia", subtitle: "Aquele docinho que faz sorrir." },
  sorvetes: { title: "Geladinho que refresca", subtitle: "Sabores pra todo gosto." },
  lanches: { title: "Mata-fome na hora certa", subtitle: "Lanches rápidos e saborosos." },
  "pizzas-salgadas": { title: "Sexta é dia de pizza", subtitle: "As melhores pizzas, quentinhas." },
  cervejas: { title: "Geladinha sempre", subtitle: "Sua cerveja favorita, na temperatura certa." },
  vinhos: { title: "Pra brindar momentos", subtitle: "Vinhos selecionados pro seu paladar." },
  acai: { title: "Energia roxa", subtitle: "Açaí cremoso, do jeito que você ama." },
  agua: { title: "Hidratação em primeiro lugar", subtitle: "Água fresquinha quando você precisar." },
  gas: { title: "Pra não ficar na mão", subtitle: "Gás entregue rápido, sem dor de cabeça." },
  cigarros: { title: "O essencial sempre por perto", subtitle: "Pratique consumo consciente." },
  medicamentos: { title: "Saúde em primeiro lugar", subtitle: "Medicamentos com agilidade e cuidado." },
  beleza: { title: "Brilhe do seu jeito", subtitle: "Beleza e autocuidado pra você." },
  suplementos: { title: "Performance no foco", subtitle: "Suplementos pra sua melhor versão." },
  snacks: { title: "Aquela vontade de petiscar", subtitle: "Snacks pra qualquer momento." },
  refrigerantes: { title: "Refresque o seu dia", subtitle: "Seu refri favorito sempre por perto." },
  sucos: { title: "Vitamina líquida", subtitle: "Sucos pra refrescar e nutrir." },
  energeticos: { title: "Energia quando você precisa", subtitle: "Pra dar aquele up no dia." },
  destilados: { title: "Pra ocasiões especiais", subtitle: "Destilados selecionados com cuidado." },
  queijos: { title: "Pra harmonizar com tudo", subtitle: "Queijos selecionados pro seu paladar." },
  organicos: { title: "Saúde direto da natureza", subtitle: "Produtos orgânicos selecionados." },
  conservas: { title: "Sabor que dura", subtitle: "Conservas pra incrementar suas receitas." },
  temperos: { title: "O segredo das receitas", subtitle: "Temperos pra dar vida aos pratos." },
  especiarias: { title: "Aroma que transforma", subtitle: "Especiarias do mundo todo." },
  graos: { title: "Base da boa alimentação", subtitle: "Grãos selecionados pra sua mesa." },
  massas: { title: "Pra um bom prato de macarrão", subtitle: "Massas pra todas as receitas." },
  azeites: { title: "Toque final perfeito", subtitle: "Azeites selecionados pra suas receitas." },
  chas: { title: "Pra relaxar a qualquer hora", subtitle: "Chás selecionados pro seu momento." },
};

export function getCategoryCopy(slug: string | undefined, name: string | undefined): CategoryCopy {
  if (slug && CATEGORY_COPY[slug]) return CATEGORY_COPY[slug];
  return {
    title: name ?? "Categoria",
    subtitle: `Tudo que você precisa em ${name ?? "uma categoria"}, entregue rápido.`,
  };
}
