UPDATE public.mf_categorias SET ativo = false;

INSERT INTO public.mf_categorias (name, slug, icon_emoji, "order", ativo) VALUES
('Acabamento','acabamento','🏗',10,true),
('Açaí','acai','🫐',20,true),
('Acessórios Pet','acessorios-pet','🐾',30,true),
('Agendas','agendas','📅',40,true),
('Água','agua','💧',50,true),
('Aquarismo','aquarismo','🐠',60,true),
('Argamassa','argamassa','🏗',70,true),
('Arte','arte','🎨',80,true),
('Aves','aves','🍗',90,true),
('Azeites','azeites','🫒',100,true),
('Bebês','bebes','👶',110,true),
('Bebidas','bebidas','🥤',120,true),
('Bebidas Geladas','bebidas-geladas','🧋',130,true),
('Beleza','beleza','💄',140,true),
('Bolos','bolos','🎂',150,true),
('Bombons','bombons','🍫',160,true),
('Brigadeiros','brigadeiros','🍫',170,true),
('Brinquedos Pet','brinquedos-pet','🧸',180,true),
('Cadernos','cadernos','📓',190,true),
('Cafés','cafes','☕',200,true),
('Calzones','calzones','🥟',210,true),
('Camas e Casinhas','camas-e-casinhas','🏠',220,true),
('Canetas','canetas','🖊️',230,true),
('Carnes Bovinas','carnes-bovinas','🥩',240,true),
('Carnes e Aves','carnes-e-aves','🥩',250,true),
('Carnes Suínas','carnes-suinas','🥓',260,true),
('Cartões e Recargas','cartoes-e-recargas','💳',270,true),
('Carvão','carvao','♨️',280,true),
('Cervejas','cervejas','🍺',290,true),
('Chás','chas','🍵',300,true),
('Cigarros','cigarros','🚬',310,true),
('Cimento','cimento','🧱',320,true),
('Coberturas','coberturas','🍯',330,true),
('Coleiras e Guias','coleiras-e-guias','🐕',340,true),
('Combos','combos','🎯',350,true),
('Confeitaria','confeitaria','🧁',360,true),
('Congelados','congelados','🧊',370,true),
('Conservas','conservas','🥫',380,true),
('Cuidados com Cabelo','cuidados-com-cabelo','💇',390,true),
('Cuidados com Pele','cuidados-com-pele','🧖',400,true),
('Dermocosméticos','dermocosmeticos','🧴',410,true),
('Destilados','destilados','🥃',420,true),
('Doces','doces','🍬',430,true),
('Elétrica','eletrica','⚡',440,true),
('Embutidos','embutidos','🌭',450,true),
('Energéticos','energeticos','⚡',460,true),
('Entradas','entradas','🥗',470,true),
('Equipamentos Médicos','equipamentos-medicos','🩺',480,true),
('Escritório','escritorio','🖥️',490,true),
('Especiarias','especiarias','🧂',500,true),
('Ferragens','ferragens','⚙️',510,true),
('Ferramentas','ferramentas','🔧',520,true),
('Frios','frios','🧀',530,true),
('Frutas','frutas','🍎',540,true),
('Frutas e Verduras','frutas-e-verduras','🥬',550,true),
('Frutos do Mar','frutos-do-mar','🦐',560,true),
('Gás','gas','🔥',570,true),
('Gelo','gelo','🧊',580,true),
('Grãos','graos','🌾',590,true),
('Hidráulica','hidraulica','🚿',600,true),
('Higiene','higiene','🧴',610,true),
('Higiene Pessoal','higiene-pessoal','🧴',620,true),
('Higiene Pet','higiene-pet','🛁',630,true),
('Hortifruti','hortifruti','🥬',640,true),
('Iluminação','iluminacao','💡',650,true),
('Impermeabilização','impermeabilizacao','🛡️',660,true),
('Importados','importados','🌍',670,true),
('Impressão','impressao','🖨️',680,true),
('Lanches','lanches','🍔',690,true),
('Laticínios','laticinios','🥛',700,true),
('Legumes','legumes','🥕',710,true),
('Limpeza','limpeza','🧹',720,true),
('Livros','livros','📚',730,true),
('Madeiras','madeiras','🪵',740,true),
('Massas','massas','🍝',750,true),
('Material Escolar','material-escolar','🎒',760,true),
('Medicamentos','medicamentos','💊',770,true),
('Medicamentos Pet','medicamentos-pet','💊',780,true),
('Mercearia','mercearia','🏪',790,true),
('Milkshakes','milkshakes','🥤',800,true),
('Mochilas','mochilas','🎒',810,true),
('Orgânicos','organicos','🌱',820,true),
('Ortopedia','ortopedia','🦴',830,true),
('Outros','outros','🏷️',840,true),
('Padaria','padaria','🍞',850,true),
('Pães','paes','🥖',860,true),
('Papel','papel','📄',870,true),
('Parafusos e Fixadores','parafusos-e-fixadores','🔩',880,true),
('Peixes','peixes','🐟',890,true),
('Petiscos','petiscos','🦴',900,true),
('Picolés','picoles','🍦',910,true),
('Pisos e Revestimentos','pisos-e-revestimentos','🪨',920,true),
('Pizzas Doces','pizzas-doces','🍕',930,true),
('Pizzas Salgadas','pizzas-salgadas','🍕',940,true),
('Porções','porcoes','🍟',950,true),
('Portas e Janelas','portas-e-janelas','🚪',960,true),
('Pratos Quentes','pratos-quentes','🍲',970,true),
('Primeiros Socorros','primeiros-socorros','🩹',980,true),
('Proteção Solar','protecao-solar','☀️',990,true),
('Queijos','queijos','🧀',1000,true),
('Ração','racao','🐶',1010,true),
('Refeições','refeicoes','📦',1020,true),
('Refrigerantes','refrigerantes','🥤',1030,true),
('Roupas Pet','roupas-pet','👕',1040,true),
('Saladas','saladas','🥗',1050,true),
('Salgados','salgados','🥐',1060,true),
('Sanduíches','sanduiches','🥪',1070,true),
('Saúde Bucal','saude-bucal','🦷',1080,true),
('Snacks','snacks','🍿',1090,true),
('Sobremesas','sobremesas','🍮',1100,true),
('Sorvetes','sorvetes','🍦',1110,true),
('Sucos','sucos','🧃',1120,true),
('Sundaes','sundaes','🍨',1130,true),
('Suplementos','suplementos','💪',1140,true),
('Temperos','temperos','🌿',1150,true),
('Tintas','tintas','🎨',1160,true),
('Tortas','tortas','🥧',1170,true),
('Trufas','trufas','🍬',1180,true),
('Tubos e Conexões','tubos-e-conexoes','🔧',1190,true),
('Verduras','verduras','🥬',1200,true),
('Vinhos','vinhos','🍷',1210,true),
('Vitaminas','vitaminas','💉',1220,true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  icon_emoji = EXCLUDED.icon_emoji,
  "order" = EXCLUDED."order",
  ativo = true;