// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Capacitor } from '@capacitor/core';
import type { Database } from './types';

const SUPABASE_URL = "https://zyhmwcsfifdepqnnrguo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5aG13Y3NmaWZkZXBxbm5yZ3VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODUwMjUsImV4cCI6MjA2MzY2MTAyNX0.TKFtW8ZUf9Jl8SN0c5EE0nomYVU8B65g6GMj4PGD1X0";

// Identifica a plataforma do chamador para que edge functions
// possam aplicar regras de freemium apenas em iOS nativo.
const platform = Capacitor.getPlatform(); // 'ios' | 'android' | 'web'
const isNative = Capacitor.isNativePlatform();
const appPlatform =
  isNative && platform === 'ios'
    ? 'ios-native'
    : isNative && platform === 'android'
      ? 'android-native'
      : 'web';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-app-platform': appPlatform,
    },
  },
});
